### ISSUE TITLE
Error while starting lab - inconsistency of default branch

### ISSUE THREAD

**Issue by bpelikan** [githubtraining/release-workflow#135]
## Bug Report

**Current behavior**
Error message while starting lab:
![image](https://user-images.githubusercontent.com/24376947/101379772-f1fb9e80-38b4-11eb-8c97-d93dd68fffa4.png)

**Reproduction**
1. Go to lab: https://lab.github.com/githubtraining/create-a-release-based-workflow
2. Start
3. On last step while starting lab (preparing repo) I get error message: 
  > There was an error while updating default branch of bpelikan/getting-started-github-apps!

**Expected behavior**
I can start lab without error.

**Possible solution**
Looking at [repository](https://github.com/cykod/AlienInvasion) that is used in this lab I can see that there default branch is `master` while in prepared repository on my account I have `main` branch. I think this is root of error.

**Comment by brianamarie** [comment]
Hello @bpelikan! I think this is similar to the other issue that you opened.

Similarly to the other issue, though we have forked from another repo, the template repo used by Learning Lab is https://github.com/githubtraining/AlienInvasion. Do you still see this error if you try again in a new browser session?

**Comment by bpelikan** [comment]
Now it's working fine. Thanks! 🙂
